In [1]:
import numpy as np


In [2]:
np.__version__

'2.2.0'

In [5]:

# %%
######### Exercise 1 ################
# Create a vector with 10 integer elements, all equal to 0.
a_list = [0 for i in range(10)]
print(a_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [6]:
a_list=[0]*10
print(a_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
a_list=[0]*10
arr =np.array(a_list)
print(arr,arr.dtype)

[0 0 0 0 0 0 0 0 0 0] int64


In [8]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr = np.zeros(10)
print(arr,arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [11]:
arr = np.zeros(10,dtype=np.int64)
print(arr,arr.dtype)

[0 0 0 0 0 0 0 0 0 0] int64


In [12]:
arr = np.zeros(10,dtype=np.int8)
print(arr,arr.dtype)

[0 0 0 0 0 0 0 0 0 0] int8


In [13]:
a=[1, 200,2]
np.array(a,dtype=np.int8)

OverflowError: Python integer 200 out of bounds for int8

In [15]:
######### Exercise 2 ################
# Create a vector with 10 integer elements, all equal to 1.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
print(np.ones(10), dtype=np.int8)

TypeError: print() got an unexpected keyword argument 'dtype'

In [19]:
######### Exercise 3 ################
# Create a vector with integer elements from 0 to 9.
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [21]:
######### Exercise 4 ################
# Create a vector with integer elements from 10 to 29.
arr=np.arange(10,30)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [22]:
######### Exercise 5 ################
# Create a vector with integer elements from 0 to 9 in reverse order.
arr=np.arange(9,-1,-1)
print(arr)

[9 8 7 6 5 4 3 2 1 0]


In [38]:
######### Exercise 6 ################
# Create a vector with 10 random elements between 0 and 1.
ARR=np.random.randint(0,2,10)
print (ARR)

[0 0 1 0 1 0 1 1 1 0]


In [39]:
ARR=np.random.randint(0,10,10) # 10 VALUES FROM 0 TO 10. 10 OT INCLUDED
print (ARR)

[6 8 6 3 4 4 1 5 7 0]


In [76]:
ARR=np.random.randint(0,10,10) /10 
print (ARR)

[0.7 0.4 0.1 0.  0.7 0.2 0.7 0.9 0.  0.7]


In [64]:
ARR=np.random.randint(0,10,3) /100 
print (ARR)

[0.09 0.05 0.01]


In [84]:
######### Exercise 7 ################
# Create a 3x3 matrix with random integer elements between 0 and 9.
np.random.randint(0,10,(3,3))

array([[3, 1, 6],
       [3, 4, 8],
       [9, 2, 7]], dtype=int32)

In [87]:
######### Exercise 8 ################
# Create a 5x5 identity matrix.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
######### Exercise 9 ################
# Add two matrices of equal dimensions (for example, 3x3).


In [ ]:
######### Exercise 10 ################
# Multiply two matrices of appropriate dimensions (for example, 2x3 and 3x2).


In [ ]:
######### Exercise 11 ################
# Transpose a matrix (for example, 3x4).


In [ ]:
######### Exercise 12 ################
# Find the maximum value in a vector.


In [ ]:
######### Exercise 13 ################
# Find the index of the maximum value in a vector.


In [ ]:
######### Exercise 14 ################
# Find the arithmetic mean of the values in a matrix.


In [ ]:
######### Exercise 15 ################
# Create a 4x4 matrix with random integer elements between 1 and 20.


In [ ]:
######### Exercise 16 ################
# Create a 6x6 diagonal matrix with diagonal elements equal to 5.


In [ ]:
######### Exercise 17 ################
# Reshape a vector of 12 elements into a 3x4 matrix.


In [ ]:
######### Exercise 18 ################
# Flatten a 3x4 matrix into a 1D array.


In [ ]:
######### Exercise 19 ################
# Create a vector of length 50 with linearly spaced values between 0 and 100.


In [ ]:
######### Exercise 20 ################
# Create a 5x5 matrix filled with a specific value (for example, 7).


In [ ]:
######### Exercise 21 ################
# Create a vector of 15 random integers between 50 and 100, and sort it.


In [ ]:
######### Exercise 22 ################
# Find the standard deviation of the values in a vector.


In [ ]:
######### Exercise 23 ################
# Replace all negative values in a vector with 0.


In [ ]:
######### Exercise 25 ################
# Create a random 4x4 matrix and compute the sum of all its elements.
